### ISSUE TITLE
Visual Studio 2019 is not supported

### ISSUE THREAD

**Issue by drusteeby** [anuviswan/Caliburn.Micro-Template-Pack#1]
Can this template pack be updated to allow installation in VS2019?

**Comment by anuviswan** [comment]
Added support for **Visual Studio 2019**. 
Markplace : [Caliburn Micro Template Pack](https://marketplace.visualstudio.com/items?itemName=anuviswan.CaliburnMicroTemplatePack)
Commit  : https://github.com/anuviswan/Caliburn.Micro-Template-Pack/commit/06b0160b71c89b11b84084c81d758b8e88658087

Special Thanks to @drusteeby for bringing it up.

**Comment by drusteeby** [comment]
Thanks @anuviswan!
